# Generated by Django 4.2.30 on 2026-05-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=1024)),
                ('thumbnail', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_productimage',
                'ordering': ['order', '-uploaded_at'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
