# Generated by Django 6.0.2 on 2026-03-17 15:24

import django.db.models.deletion
import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_tag_category_note_category_note_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=notes.models.generate_share_token, help_text='Unique token used to access the shared note.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration datetime for the share link.', null=True)),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times this share link has been accessed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the share link was created.')),
                ('note', models.ForeignKey(help_text='The note being shared.', on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='notes.note')),
            ],
            options={
                'verbose_name': 'Share Link',
                'verbose_name_plural': 'Share Links',
                'ordering': ['-created_at'],
            },
        ),
    ]
