# Generated by Django 6.0.2 on 2026-03-02 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the note (max 200 characters).', max_length=200)),
                ('content', models.TextField(help_text='Full content of the note.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the note was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the note was last updated.')),
                ('owner', models.ForeignKey(help_text='The user who owns this note.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-updated_at'],
            },
        ),
    ]
